### ISSUE TITLE
End-to-end testing

### ISSUE THREAD

**Issue by ebaron** [cryostatio/cryostat-operator#113]
Now that we have some unit tests, we should start looking at end-to-end testing to help detect issues such as #112 early. Controller-runtime provides an `envtest` package to help with this.

https://book.kubebuilder.io/reference/envtest.html

**Comment by andrewazores** [comment]
I think the setup for this ends up getting taken care of as a side-effect of the operator-sdk 1.x upgrade.

https://sdk.operatorframework.io/docs/building-operators/golang/references/envtest-setup/

More tests could probably be added, or maybe the existing tests enhanced if there are new capabilities offered by envtest - I don't really understand the difference yet.

**Comment by ebaron** [comment]
Closing this in favour of https://github.com/cryostatio/cryostat-operator/issues/448 and https://github.com/cryostatio/cryostat-operator/issues/504.
