### ISSUE TITLE
"Installer Script" for setting up Operator

### ISSUE THREAD

**Issue by andrewazores** [cryostatio/cryostat-operator#144]
Does it make sense to create a simpler, more "streamlined" feeling (un)installer script for setting up the Operator? This would be useful for us in the interim before we're published in any OperatorHub or similar registries, as well as useful for end users who want to install without going through these Hubs. This would basically just wrap around the existing various YAML files for CRDs and ServiceAccounts with the Makefile or some shell script that would basically do the same job as `make deploy` or `make undeploy`. The goal simply being to make installation "feel" easier than cloning the repo and running `make` instructions.

**Comment by ebaron** [comment]
Something like a big YAML file with all the resources in one? Then you can just `kubectl/oc apply -f big.yaml`? This is what cert-manager does, and how we install it with `make cert-manager`.

**Comment by andrewazores** [comment]
Yea, something like that - it was initially @jiekang's idea here, but I think the thought is just to have something as close to a "one-click install" as possible directly from GitHub. So one big YAML file that we can reference in the README sounds good to me, too. This should probably be tagged as a release here on GitHub so it's easy to refer to specific versions of it, too.

**Comment by jiekang** [comment]
Yeah, basically and something we can deliver as a tarball. So download off release section, untar, run script. Or at least that was the idea.

**Comment by jiekang** [comment]
A large yaml file in the repo that we instruct users to `kubectl/oc apply -f` is also good too. It's a little more transparent than the current makefile setup.
