### ISSUE TITLE
Remove 'LISTEN' env vars

### ISSUE THREAD

**Issue by andrewazores** [cryostatio/cryostat-operator#201]
The `LISTEN` env vars (ex. `CRYOSTAT_LISTEN_HOST`) are no longer used by Cryostat and can/should therefore be removed from the Operator, since setting them no longer has any effect. These were previously used to control command channel binding on raw TCP sockets, but now that the command (notification) channel is only implemented over WebSocket, the bound interface and port always correspond to the `WEB` env var values.

**Comment by ebaron** [comment]
Should the `command` service/route/ingress be removed as well?

**Comment by andrewazores** [comment]
I suppose so. The notification channel URL now always has the same domain and port as the `core` service, but with the `ws(s)://` protocol and a static path. That probably doesn't warrant a separate service/route/ingress anymore.

Also, we should rename the path for that channel. It's still `/api/v1/command`, but it should now be `notification(s)` instead of `command`.

**Comment by andrewazores** [comment]
https://github.com/cryostatio/cryostat/issues/478

**Comment by ebaron** [comment]
@jaadbarg you mentioned you were interested in this one? I think if you comment, GitHub will let me assign you to it.

**Comment by jaadbarg** [comment]
@ebaron sure, sounds great!

**Comment by ebaron** [comment]
We should mark `NetworkConfigurationList.CommandConfig` as deprecated: https://github.com/cryostatio/cryostat-operator/blob/5e77d600318654a45d23e0ff9c2b1cbeaedd3f93/api/v1beta1/cryostat_types.go#L116

Here is how to mark a field as deprecated in Golang: https://github.com/golang/go/wiki/Deprecated. The comment can be something like `Deprecated: CommandConfig is no longer used.`

Similarly, our documentation should remove references to `CommandConfig`: https://github.com/cryostatio/cryostat-operator/blob/5e77d600318654a45d23e0ff9c2b1cbeaedd3f93/docs/config.md#network-options.
