### ISSUE TITLE
Sync Recordings with Cryostat

### ISSUE THREAD

**Issue by ebaron** [cryostatio/cryostat-operator#205]
The operator should create Recording objects in response to a user creating a recording in Cryostat outside of the operator (e.g. via web client, HTTP API). Perhaps we can use Cryostat's notification channel to do this.

**Comment by ebaron** [comment]
Having the operator listen on Cryostat's notification channel may not scale if the operator becomes cluster-scoped. We would have to listen on an arbitrary number of WebSockets, one for each Cryostat deployed by the operator. @andrewazores any thoughts on this?

**Comment by andrewazores** [comment]
That's true. Perhaps it would only make sense to deploy the Operator at cluster-scope if/when we can also support that deployment scenario in Cryostat itself, so that there is still a 1:1 relationship of Operators to Cryostats. I think that's eventually something we want to support in Cryostat anyway, since deploying *n* Cryostats for *n* namespaces is already not the best scalability-wise.

**Comment by ebaron** [comment]
Makes sense. In that case, it should be fine to move forward with using the notification channel in the operator, if that's how we want to handle this.

**Comment by andrewazores** [comment]
I think so - this is pretty much exactly the scenario the notification channel exists for. We definitely want the HTTP API and CRD API to reflect the same system state and as close to real-time-synchronized as possible. I imagine as a user it would be very confusing and seem like something was very broken if I could create a recording in the web-client and see it there, even after closing/reopening the tab, trying a new browser, etc., but never see that same recording appear as a Custom Resource. But then if I do it in reverse and create a recording via CR, it would appear instantaneously in the web-client(!?).

**Comment by ebaron** [comment]
I suppose there's still a chance these could fall out of sync, if there's a network issue or the operator pod crashes. Perhaps we can worry about that later though.

**Comment by andrewazores** [comment]
Right, that's true. Not too much we can do about a network issue if we don't detect it, but perhaps if we do detect a problem we can do an HTTP poll to re-sync. An initial HTTP poll on startup, after (re-)establishing the notification channel connection, would also help re-sync if the operator crashes.

**Comment by ebaron** [comment]
I encountered a bit of a problem mapping the target listed in the notification to a Pod. In the operator's API, the Recording object needs to reference a FlightRecorder object, which in turn references a target Pod.

The notification contains the JMX service URL, which gives the pod IP:
`
{"meta":{"category":"RecordingCreated","type":{"type":"application","subType":"json"},"serverTime":1622145272},"message":{"recording":"test","target":"service:jmx:rmi:///jndi/rmi://10.217.0.13:9096/jmxrmi"}}
`

I haven't yet come across a way of efficiently mapping this pod IP back to a pod name. Reverse DNS lookup helps a bit for Pods created by Deployments, but not in the general case. [1]
```
$ nslookup 10.217.0.13
13.0.217.10.in-addr.arpa	name = 10-217-0-13.quarkus-test.cryostat-operator-system.svc.cluster.local.
```

[1] https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#a-aaaa-records-1

**Comment by andrewazores** [comment]
https://github.com/cryostatio/cryostat/issues/280

I think an implementation solving the above issue would unblock what you're facing here.

**Comment by ebaron** [comment]
> [cryostatio/cryostat#280](https://github.com/cryostatio/cryostat/issues/280)
> 
> I think an implementation solving the above issue would unblock what you're facing here.

Possibly, but even the existing alias would help because it's the pod name. I think the problem is more that there's no way to get the ServiceRef from the target ID/JMXServiceURL without looping through them all. For example, the Recording POST handler only knows the target ID it was provided, so it can't provide any more detailed information in the notification without doing a linear search for the ServiceRef each time.

**Comment by andrewazores** [comment]
Ah, yes that's also true. I hadn't filed an issue for it but this same deficiency is on my radar, although I'm not sure how best to tackle it yet. We could simply maintain a mapping of service URLs to ServiceRefs for reverse lookup, but that's really just a bandaid fix. A better solution might be to actually and finally decouple `targetId`s from service URLs - when we detect a new target and create a ServiceRef for it, maybe we should actually generate a unique ID for that target and use that ID to reference it everywhere that we currently expect the service URL as the `"targetId"`. We could then cache these IDs for reverse lookup of ServiceRefs.

This also has the side benefit of not allowing API requests to arbitrary targets, at least not without first going through the API to create a custom target definition, which could do some kind of validation on the provided URL beyond making sure it's a well-formed URL.

**Comment by ebaron** [comment]
Sounds like a good idea. If you were to use the pod name and perhaps the namespace in the target ID for the Kubernetes case, you could even avoid having to cache the mappings since you could just look up the pod directly to recreate the ServiceRef.

**Comment by ebaron** [comment]
The operator's Recording API has been deprecated with #349.
