### ISSUE TITLE
OpenShift SDN Connectivity is broken

### ISSUE THREAD

**Issue by andrewazores** [cryostatio/cryostat-operator#255]
Not exactly an Operator issue, but Cryostat+OpenShift related.

There are connectivity issues between Cryostat and target pods for intra-cluster JMX connections when using OpenShift SDN, where some large proportion of network requests fail.

**Comment by ebaron** [comment]
This bug is caused by JDP autodiscovery, which we don't need in Kubernetes environments. See: https://bugzilla.redhat.com/show_bug.cgi?id=1979733
