### ISSUE TITLE
Create Recording Duration does not accept integer value

### ISSUE THREAD

**Issue by sefroberg** [cryostatio/cryostat-operator#256]
After installing Cryostat onto an OpenShift cluster off the v2 branch, attempting to create a recording from the Cryostat Operator will not accept any number in the "Duration" field of the Create Recording form view.
1. Install Cryostat onto your OpenShift cluster.
2. Log into your OpenShift cluster with Kubeadmin account.
3. Select "Installed Operators" in the left column in the "Operators" section.
4. Select "Cryostat".
5. Select Create instance under Recording.
6. Enter a number in the "Duration*" field. I entered "30".
7. Select state Running.
7. Leave everything else at the default and then hit create at the bottom.
8. Get an error: 
```
   Fix the following errors:

    Error "Invalid value: "integer": spec.duration in body must be of type string: "integer"" for field "spec.duration".
```

**Comment by andrewazores** [comment]
In the duration field, does it accept the value if you enter `"30"` (with the quotes), so that the value is a string rather than being interpreted as numeric?

**Comment by sefroberg** [comment]
@andrewazores yes it does.

**Comment by ebaron** [comment]
This should be changed to `xDescriptors={"urn:alm:descriptor:com.tectonic.ui:text"}`, and the expected format for the duration should be mentioned in the description. It's expected to be a string with a number and a unit, e.g. `30s` `1h30m`: https://pkg.go.dev/time#Duration
