### ISSUE TITLE
Release on OperatorHub.io

### ISSUE THREAD

**Issue by ebaron** [cryostatio/cryostat-operator#279]
We should make Cryostat Operator releases available on https://operatorhub.io/

**Comment by ebaron** [comment]
A guide on contributing an operator to OperatorHub: https://operatorhub.io/contribute. We will be using the Bundle format, not the PackageManifest format.

**Comment by jiekang** [comment]
The docs seem to be outdated in one area or another as https://k8s-operatorhub.github.io/community-operators/packaging-operator/ suggests `semver-mode` being the default, as well as another mode, `semver-skippatch`.

After reading the explanation I linked, I recommend `semver-skippatch` or `semver-mode`

**Comment by ebaron** [comment]
> After reading through the contribution docs, Hareet and I had a few questions:
> 
>     1. Which version of the cryostat operator bundle should we use? This one from the v2 branch? https://github.com/cryostatio/cryostat-operator/tree/v2

You'll want the `v2.0.0` tag. https://github.com/cryostatio/cryostat-operator/tree/v2.0.0
> 
>     2. The [Operator Publishing / Review Settings](https://k8s-operatorhub.github.io/community-operators/operator-ci-yaml/) > Operator Versioning lists two version modes: `updateGraph: replaces-mode` and `updateGraph: semver-mode`. Which mode should we choose and why?

I think `semver-mode` is the way to go. If I understand the docs correctly, `replaces-mode` means we'll have to manually manage the update graph. `semver-skippatch` may be fine but complicates testing by adding additional upgrade paths (e.g. need to ensure both 2.0.0 -> 2.0.1 -> 2.1.0 and 2.0.0 -> 2.1.0 work).

> 
>     3. We were wondering what the `replaces-mode` description meant by saying, "It means, that there is a possibility to omit some versions from the update graph. Best practice is to put them to a separate channel then." We also found some [channel naming conventions](https://olm.operatorframework.io/docs/best-practices/channel-naming/) and were wondering how the channel name `alpha` (from [bundle.Dockerfile](https://github.com/cryostatio/cryostat-operator/blob/v2/bundle.Dockerfile)) affects the operator versioning?

We've been using the `alpha` for nightly builds essentially. In the `v2.0.0` tag, you'll see we use the `stable` channel instead. Users subscribing to the stable channel should get whatever the newest release is, and be able to upgrade as newer releases come out.

> 
>     4. To setup the [testing pre requisites](https://k8s-operatorhub.github.io/community-operators/testing-operators/#pre-requisites), we decided to start a minikube cluster. Hareet's cluster started successfully, but I ran into some errors. Here's what I've tried so far and my logs. Any ideas?
> 
> 
> ```
> sudo dnf install ansible
> systemctl start docker
> sudo dnf install kubernetes-kubeadm
> sudo swapoff -a
> systemctl enable kubelet.service
> systemctl start kubelet
> minikube start
> ```
> 
> Fri Nov 12 18:36: http://pastebin.test.redhat.com/1008065 Today's logs (after noticing the warning from Fri saying 'please enable kubelet.service`): http://pastebin.test.redhat.com/1008328

I've been using the kvm2 driver to run Minikube [1]. Maybe that will help if that's not what you're doing already. Essentially `minikube start --driver=kvm2`, and if that works make it default with: `minikube config set driver kvm2`.

[1] https://minikube.sigs.k8s.io/docs/drivers/kvm2/

**Comment by jan-law** [comment]
> I've been using the kvm2 driver to run Minikube

Thanks, that worked for me. It turns out my driver was set to Docker by default, and I needed to enable hardware virtualization before minikube could use kvm2.

**Comment by hareetd** [comment]
We were able to complete manual testing of the operator through the process detailed here: https://k8s-operatorhub.github.io/community-operators/testing-operators/.

However, when we try to locally run the automatic CI test suite (see https://k8s-operatorhub.github.io/community-operators/operator-test-suite/) we run into issues with our Kubernetes setup, specifically with `kind`, `kubeadm` and `kubelet`. 

The following are Janelle's logs but I have the same results as well:

1. After running "bash <(curl -sL https://raw.githubusercontent.com/redhat-openshift-ecosystem/community-operators-pipeline/ci/latest/ci/scripts/opp.sh) \
kiwi,lemon \
operators/cryostat-operator/2.0.0 \
https://github.com/jalaw/community-operators \
cryostat-operator" : 

http://pastebin.test.redhat.com/1008727

2. Systemctl logs for kubelet: http://pastebin.test.redhat.com/1008728

**Comment by jan-law** [comment]
The [OperatorHub.io docs](https://k8s-operatorhub.github.io/community-operators/packaging-operator/) (scroll to bottom of page) also recommend adding info about any manual pre-requisite steps and links to more information in the CSV. This is the catalog preview using https://operatorhub.io/preview. The github repo link is already included, but should we mention anything about installing cert-manager or add any other links to documentation in the description?
![image](https://user-images.githubusercontent.com/84587295/142080489-4d2a369d-19b2-4281-a142-03e906179381.png)
![image](https://user-images.githubusercontent.com/84587295/142080533-c4329223-d1e0-4715-91a4-b1ce8e0eb537.png)

**Comment by jiekang** [comment]
Yeah, I'd add cert-manager installation as a manual pre-req.

**Comment by ebaron** [comment]
> Yeah, I'd add cert-manager installation as a manual pre-req.

Yes please, this should go into the CSV in this repo as well. Created an issue for it: https://github.com/cryostatio/cryostat-operator/issues/299

> We were able to complete manual testing of the operator through the process detailed here: https://k8s-operatorhub.github.io/community-operators/testing-operators/.
> 
> However, when we try to locally run the automatic CI test suite (see https://k8s-operatorhub.github.io/community-operators/operator-test-suite/) we run into issues with our Kubernetes setup, specifically with `kind`, `kubeadm` and `kubelet`.

That's unfortunate :(. I haven't used Kind before, but I'll find some time soon to try it out myself.

**Comment by ebaron** [comment]
I tried to get the OperatorHub.io test suite to run with Podman, but it doesn't seem supported at the moment. I installed Docker using the guide here: https://fedoramagazine.org/docker-and-fedora-32/, and the test suite seems to run for me now. I get this failure, which I think indicates we need to add `updateGraph: semver-mode` to our ci.yaml:
```
TASK [operator_info : Index mode] **********************************************
task path: /playbooks/upstream/roles/operator_info/tasks/op_info.yml:57
fatal: [localhost]: FAILED! => 
  msg: |-
    The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'updateGraph'
  
    The error appears to be in '/playbooks/upstream/roles/operator_info/tasks/op_info.yml': line 57, column 7, but may
    be elsewhere in the file depending on the exact syntax problem.
  
    The offending line appears to be:
  
  
        - name: "Index mode"
          ^ here
```

**Comment by hareetd** [comment]
Sounds good, we'll try the Docker setup then. Thanks!

**Comment by ebaron** [comment]
We may want to include this piece of documentation in the CSV description as well:
https://github.com/cryostatio/cryostat-operator/blob/v2.0.0/docs/config.md#network-options

Since this release is primarily intended to run on plain Kubernetes, the user will have to define the Ingress specs accordingly, which is not all that obvious.

**Comment by jan-law** [comment]
The test suite runs and passes all tests with Docker now: https://gist.github.com/jan-law/572220f1867edce233f57db5406847dd

I've also added the cert-manager docs and Ingress config docs to the CSV. 

Is there anyone I should add/remove as a reviewer in the `ci.yaml` file?
https://k8s-operatorhub.github.io/community-operators/operator-ci-yaml/
```
---
updateGraph: semver-mode
reviewers:
 - ebaron
 - jan-law
 - hareetd
 - jiekang
```

**Comment by ebaron** [comment]
> The test suite runs and passes all tests with Docker now: https://gist.github.com/jan-law/572220f1867edce233f57db5406847dd
> 
> I've also added the cert-manager docs and Ingress config docs to the CSV.

Great news!
 
> Is there anyone I should add/remove as a reviewer in the `ci.yaml` file? https://k8s-operatorhub.github.io/community-operators/operator-ci-yaml/
> 
> ```
> ---
> updateGraph: semver-mode
> reviewers:
>  - ebaron
>  - jan-law
>  - hareetd
>  - jiekang
> ```

I would add @andrewazores as well.

**Comment by ebaron** [comment]
> I tried to get the OperatorHub.io test suite to run with Podman, but it doesn't seem supported at the moment. I installed Docker using the guide here: https://fedoramagazine.org/docker-and-fedora-32/ [...]

One thing I noticed after following this guide is I get the following error when running `crc setup`:
```
Failed to start libvirt 'crc' network 
 exit status 1: error: Failed to start network crc
error: error from service: changeZoneOfInterface: COMMAND_FAILED: 'python-nftables' failed: 
JSON blob:
{"nftables": [{"metainfo": {"json_schema_version": 1}}, {"add": {"rule": {"family": "inet", "table": "firewalld", "chain": "filter_IN_libvirt_allow", "expr": [{"match": {"left": {"payload": {"protocol": "udp", "field": "dport"}}, "op": "==", "right": 67}}, {"match": {"left": {"ct": {"key": "state"}}, "op": "in", "right": {"set": ["new", "untracked"]}}}, {"accept": null}]}}}, {"add": {"rule": {"family": "inet", "table": "firewalld", "chain": "filter_IN_libvirt_allow", "expr": [{"match": {"left": {"payload": {"protocol": "udp", "field": "dport"}}, "op": "==", "right": 547}}, {"match": {"left": {"ct": {"key": "state"}}, "op": "in", "right": {"set": ["new", "untracked"]}}}, {"accept": null}]}}}, {"add": {"rule": {"family": "inet", "table": "firewalld", "chain": "filter_IN_libvirt_allow", "expr": [{"match": {"left": {"payload": {"protocol": "tcp", "field": "dport"}}, "op": "==", "right": 53}}, {"match": {"left": {"ct": {"key": "state"}}
```

It seems like one of the steps mentioned in the article is no longer required and causes a conflict with the moby-engine package. To rectify this, I ran:
```
sudo firewall-cmd --zone=trusted --remove-interface=docker0 --permanent
sudo systemctl restart firewalld.service
```

After this, the OperatorHub test suite still runs properly and `crc setup` also works. I hope this helps, if you run into the same problem.

**Comment by jan-law** [comment]
>  I hope this helps, if you run into the same problem.

Good to know. I've been using kind for the test suite and it's working well.

Now that all of the prerequisite steps are complete, I'll work with Hareet to open a PR

**Comment by ebaron** [comment]
Thanks! When you've opened the PR, can you link it in a comment here?

**Comment by jan-law** [comment]
@ebaron, @hareetd and I followed your [network options readme](https://github.com/cryostatio/cryostat-operator/blob/v2.0.0/docs/config.md#network-options) and ran into an error when testing cryostat in minikube: `No route to host: testing.cryostat-grafana/192.168.39.129:443`. 
```
NAME                                                    READY   STATUS    RESTARTS      AGE
cryostat-operator-controller-manager-5696448764-t2lkw   1/1     Running   0             35m
cryostat-sample-57858cd788-psw8c                        2/3     Running   7 (45s ago)   21m
```
```
$ kubectl get ingress
NAME                      CLASS   HOSTS                      ADDRESS     PORTS     AGE
cryostat-sample           nginx   testing.cryostat           localhost   80, 443   112s
cryostat-sample-command   nginx   testing.cryostat-command   localhost   80, 443   112s
cryostat-sample-grafana   nginx   testing.cryostat-grafana   localhost   80, 443   112s
```
We weren't sure which of the [minikube ingress commands](https://kubernetes.io/docs/tasks/access-application-cluster/ingress-minikube/) to follow, so we tried the following steps: https://gist.github.com/jan-law/69a862723089c68bead9b0056c242b41

full logs are here: https://gist.github.com/jan-law/0d11d9a72d898df56e1bd946b95b07d8

yaml files are here: https://gist.github.com/jan-law/16a808e0205e99d1d3e8878a681769e9

**Comment by ebaron** [comment]
It looks right to me, very strange. Can you show me the YAML for the Ingress objects too?

**Comment by jan-law** [comment]
`kubectl get ingress -o yaml`: https://gist.github.com/jan-law/f315eb15e703c8e8b65af632746e9835

**Comment by ebaron** [comment]
@andrewazores encountered this issue as well. The Ingress status is showing `localhost` and not the Minikube IP. I forget exactly how we resolved the problem, but try restarting from scratch: Delete the Cryostat CR, uninstall the operator, stop Minikube, restart computer.

**Comment by andrewazores** [comment]
I'm not sure what I did either to "resolve" it - I just started from scratch as Elliott says, and somehow it came back with the expected IP address instead. I thought that I repeated all the steps the same way but perhaps I unknowingly did something incorrectly the first time and correctly the second time.

**Comment by hareetd** [comment]
So it turns out my Ingress routing is actually working. If I go to `https://testing.cryostat/` I can see the web UI and the WebSocket connection is accepted. 

What's weird is that I followed the exact same steps and my Ingress status also shows `localhost` but mine is working for some reason...

On a side note, I left the UI untouched for a few minutes and this is the result:

![image](https://user-images.githubusercontent.com/41028544/143500256-37980f3a-0005-4e4f-956c-41b3c0c483ae.png)

Before leaving the UI I had selected the Cryostat instance as a target but didn't complete authentication.

**Comment by andrewazores** [comment]
That's looking a lot like https://github.com/cryostatio/cryostat-web/issues/338 , which also came out of SSL/TLS misconfiguration issues when using Kubernetes Ingress...

**Comment by hareetd** [comment]
I was just about to link Janelle's comment on that issue: https://github.com/cryostatio/cryostat-web/issues/338#issuecomment-973142068. My situation is similar but the errors and reconnection/dropping of the `WebSocket` occur at a much more frequent rate than 1-minute intervals.

**Comment by hareetd** [comment]
Logs for reference: https://gist.github.com/hareetd/64766c5520ca80dbc741a6f50a0f393f

**Comment by ebaron** [comment]
Assuming the `testing.cryostat-grafana` hostname is also defined in /etc/hosts, then it seems like maybe the hostname is working on your local machine, but not inside the Minikube VM. Let me know if the full process outlined here helps: https://github.com/cryostatio/cryostat-operator/issues/279#issuecomment-979461067

**Comment by hareetd** [comment]
Still the same issue, unfortunately i.e. repeated `WebSocket` connection drops and errors.

**Comment by ebaron** [comment]
@hareetd What do you get from `kubectl get pods -n ingress-nginx`?

**Comment by hareetd** [comment]
@ebaron 

![image](https://user-images.githubusercontent.com/41028544/143658769-5b15792b-07bb-4812-b263-b853effc090f.png)

Which seems correct judging by the docs: https://kubernetes.io/docs/tasks/access-application-cluster/ingress-minikube/#enable-the-ingress-controller

**Comment by ebaron** [comment]
Indeed, that looks fine. Can you past the relevant line from /etc/hosts?

**Comment by hareetd** [comment]
`192.168.39.246 testing.cryostat testing.cryostat-command testing.cryostat-grafana`

Where the IP address is the result from running `minikube ip`.

**Comment by ebaron** [comment]
@hareetd Do you know if you're using the KVM2 driver like @jan-law and I are? You should be able to find out by using:
```
$ jq .Driver ~/.minikube/profiles/minikube/config.json 
"kvm2"
```

If you're using the Docker driver, this may be the issue you're facing: https://github.com/kubernetes/minikube/issues/7802

**Comment by hareetd** [comment]
I'm using the same driver, unfortunately. 

Logs: https://gist.github.com/hareetd/ce325767a808edee4cd45ee9e6f2e0b9

For some reason, even though the behaviour on the web client is the same, the `Exceptions` thrown. In the previous logs, an `UnknownHostException` was repeatedly thrown when attempting to query `testing.cryostat-grafana`. 

Now, a `NoStackTraceTimeoutException` is thrown when attempting a `HTTP GET` for the health of the `testing.cryostat-grafana` container, followed by repeated connecting and dropping of the `WebSocket` connection.

**Comment by jan-law** [comment]
> try restarting from scratch: Delete the Cryostat CR, uninstall the operator, stop Minikube, restart computer.

Thanks, I'm able to see the web-client with these steps now. The Ingress addresses still show localhost.
```
NAME                      CLASS   HOSTS                      ADDRESS     PORTS     AGE
cryostat-sample           nginx   testing.cryostat           localhost   80, 443   17m
cryostat-sample-command   nginx   testing.cryostat-command   localhost   80, 443   17m
cryostat-sample-grafana   nginx   testing.cryostat-grafana   localhost   80, 443   17m
```
Here are my most recent logs showing the webSocket connections getting dropped after to many concurrent connections. I don't see the same exceptions as Hareet: https://gist.github.com/jan-law/992090079a5e110811f8d1ea08b405a4

**Comment by ebaron** [comment]
> Here are my most recent logs showing the webSocket connections getting dropped after too many concurrent connections. I don't see the same exceptions as Hareet: https://gist.github.com/jan-law/992090079a5e110811f8d1ea08b405a4

@jan-law does this have a known fix in -web? I know you've done some work on the WebSocket connections there recently.

**Comment by jan-law** [comment]
@ebaron the main -web branch has some changes to the way the frontend handles webSocket connections. I'll build and test the latest -web branch on minikube to see what happens

**Comment by ebaron** [comment]
@jan-law Sounds good. If you just do a `make deploy` from the operator's main branch it should get you changes up to https://github.com/cryostatio/cryostat-web/commits/956f782ec9c19e9f144ab3185630a0a6bd2e790b. `kubectl describe deploy cryostat-sample` should show the `cryostat` image with 2.1.0-SNAPSHOT.

**Comment by jan-law** [comment]
@ebaron With the `cryostat:2.1.0-SNAPSHOT` image on minikube, the error notifications don't appear anymore. The websocket connection still disconnects and reconnects every 60s as described in https://github.com/cryostatio/cryostat-web/issues/338#issuecomment-973142068
![image](https://user-images.githubusercontent.com/84587295/144123277-35c7d256-8bd3-4758-a349-f06ef6a20bea.png)

**Comment by ebaron** [comment]
@jan-law Try adding these annotations to each Ingress:
```
nginx.ingress.kubernetes.io/proxy-read-timeout: 3600
nginx.ingress.kubernetes.io/proxy-send-timeout: 3600
```
This seems to be the recommended solution from the NGINX Ingress documentation: https://kubernetes.github.io/ingress-nginx/user-guide/miscellaneous/#websockets

**Comment by jiekang** [comment]
Do we need a constant websocket connection? It sounds like the timeout is based on inactivity, which sounds sensible on it's own. Can we accommodate that functionality and just re-connect the next time we need to use it? Alternatively we can send keep-alive pings from either side through the connection and if it makes sense, have an increase in the timeout length. An open and unused connection doesn't sound ideal.

**Comment by jiekang** [comment]
Is the behavior robust when the other side of the connection randomly dies?

**Comment by jan-law** [comment]
> Is the behavior robust when the other side of the connection randomly dies?

The main -web branch automatically retries the connection whenever the WebSocket connection gets disconnected for any reason (other than an authorization failure). In the case of a timeout, a user would see the page refresh briefly and two info-level notifications would appear inside the notification drawer: `WebSocket connection lost` and `WebSocket Client Activity: Client at 172.17.0.6:46334 accepted`

**Comment by andrewazores** [comment]
The constant connection is used for notification emission from the server, so it's not feasible for the client side to re-open the connection on-demand - it doesn't know when demand is. We could send application-level keep-alive pings from either side (or both) and just ignore them in the web-client so they don't produce visual noise.

**Comment by jiekang** [comment]
Okay. I think websocket has spec/definitions for keep-alive via special Ping/Pong messages. Maybe we can investigate that then.

**Comment by jan-law** [comment]
>If the 3600 timeout is useful for packaging/productization/downstream type things like OperatorHub then I think it's probably a good idea to include that configuration for now. Once we have an upstream release that includes application-level keepalive then the downstream configuration for increasing the timeout can be removed.

_Originally posted by @andrewazores in https://github.com/cryostatio/cryostat/issues/757#issuecomment-983070243_

Now that #311 is merged, should we go ahead with submitting an OperatorHub PR, or would you rather we include the keepalive pings in the OperatorHub PR?

**Comment by andrewazores** [comment]
I'm okay with the initial OperatorHub PR just containing the `3600` timeout "fix". The keepalive pings will take some more time to get implemented in upstream Cryostat and -web, and then some more time before they make it into a released version that we can tag and reference in the OperatorHub.

**Comment by jan-law** [comment]
PR opened here: https://github.com/k8s-operatorhub/community-operators/pull/481

**Comment by ebaron** [comment]
This is now live! https://operatorhub.io/operator/cryostat-operator

Congrats and thanks @jan-law and @hareetd!

**Comment by ebaron** [comment]
FYI: I filed an issue to update the install guide on the website for this change: https://github.com/cryostatio/cryostatio.github.io/issues/34
