### ISSUE TITLE
Release version 2.0.0

### ISSUE THREAD

**Issue by ebaron** [cryostatio/cryostat-operator#281]
- [x] Update jfr-datasource and dashboard image versions to 2.0.0, and backport (https://github.com/cryostatio/cryostat-operator/pull/282, https://github.com/cryostatio/cryostat-operator/pull/283)
- [x] Set operator and core version to 2.0.0 and update CSV in v2 branch (https://github.com/cryostatio/cryostat-operator/pull/284)
- [x] Tag release (https://github.com/cryostatio/cryostat-operator/releases/tag/v2.0.0)
- [x] Push build to Quay (quay.io/cryostat/cryostat-operator:2.0.0)
- [x] Push bundle build to Quay (quay.io/cryostat/cryostat-operator-bundle:2.0.0)
- [x] Bump version to 2.0.1-dev and update CSV in v2 branch (https://github.com/cryostatio/cryostat-operator/pull/285)

**Comment by mhagnumdw** [comment]
Hi! When will the next release be? I'm need of things that are already in the master.
