### ISSUE TITLE
Upgrade Operator SDK to at least 1.8.2

### ISSUE THREAD

**Issue by ebaron** [cryostatio/cryostat-operator#287]
The operator's service account should not be included in the bundle. It should instead be created and managed by OLM. Having this service account present in the bundle results in the following scorecard failure:
`Error: Value cryostat-operator-service-account: invalid service account found in bundle. sa name cannot match service account defined for deployment spec in CSV`

Operator SDK excludes the operator's service account when generating bundles with this fix: https://github.com/operator-framework/operator-sdk/pull/5120. This fix is present in 1.8.2, 1.9.2, 1.10.1, 1.11.0+. We should upgrade to one of these versions.

**Comment by ebaron** [comment]
We are currently using Operator SDK 1.5.0. The migration guide outlines steps to be taken when upgrading: https://sdk.operatorframework.io/docs/upgrading-sdk-version/

**Comment by tthvo** [comment]
Hi @ebaron I am wondering which release version we are aiming to upgrade to? 

From the test suite of the operator-community repo, they are using `v1.16.0`. Would `v1.16.0` be our target?

https://github.com/redhat-openshift-ecosystem/operator-test-playbooks/blob/992cb71004646184da86688a48466e7de84dba4b/roles/install_operator_prereqs/defaults/main.yml#L3

**Comment by ebaron** [comment]
I would say target the newest release, unless some major incompatibility is mentioned in the migration docs between 1.16 and the newest.
