### ISSUE TITLE
Add possibility to configure connection URL for FlightRecorder

### ISSUE THREAD

**Issue by spriadka** [cryostatio/cryostat-operator#302]
I've been trying to create scenario, where cryostat instance would connect to application running on WildFly. I've tried going with this guide: https://developers.redhat.com/articles/2021/10/26/configuring-java-applications-use-cryostat#step_2__configure_the_application_for_jmx. The FlightRecorder instance showed up instantly after naming the JMX port `jfr-jmx` but when I was hitting connection issues when trying to create recordings. Then I went with this guide: https://developers.redhat.com/articles/2021/11/02/java-monitoring-custom-targets-cryostat?source=sso#prerequisites_and_setup, where I've created the JVM target manually in the console and was successful. 
Overall, I think it would be nice to have possibility to configure connection URL for applications (e.g running on WildFly), that do not have default `/jmxrmi` endpoint available.

**Comment by ebaron** [comment]
Hi @spriadka, were you able to successfully create a recording for your custom target using the Cryostat web application? I understand this functionality is missing from the FlightRecorder Kubernetes API, but I would like to first ensure the functionality works in the Cryostat web application and HTTP API.

**Comment by spriadka** [comment]
Hi @ebaron
Thank you for reaching out soon :) And yes, I was able to create recordings for my custom target.

**Comment by ebaron** [comment]
Hi @spriadka, we're considering deprecating the FlightRecorder/Recording API. It's challenging from a maintenance perspective to mirror the Cryostat data/API as a Kubernetes API. Currently there are several missing features like this one you mentioned and also #205. Is being able to manage recordings through the Kubernetes API a valuable feature for you?
