### ISSUE TITLE
Support Service annotations

### ISSUE THREAD

**Issue by misastovicek** [cryostatio/cryostat-operator#304]
Currently there is no way how to change the Service type to anything else but LoadBalancer. On top of that annotations can not be set and so when the Cryostat is deployed into a public cloud where the decision whether to create external or internal Load Balancer is based on annotations, the deployment always creates public Load Balancer.

There should be a way to set the annotations so that one can decide whether to deploy an external or internal Load Balancer among other configurations of those Load Balancers which are controlled by the annotations.

**Comment by ebaron** [comment]
Excellent suggestion! We'll look at adding this in the near future.

**Comment by ebaron** [comment]
Hi @misastovicek, customization of the services' type, ports, labels and annotations have been merged and will be present in our next feature release.

**Comment by misastovicek** [comment]
Hi @ebaron, thanks a lot!
