### ISSUE TITLE
Clarify "minimal" property

### ISSUE THREAD

**Issue by ebaron** [cryostatio/cryostat-operator#350]
The minimal property currently states that no web UI is included, but that's not the case:
https://github.com/cryostatio/cryostat-operator/blob/3948e7dedd0c25f1de14a47f06dcde3196a014fd/api/v1beta1/cryostat_types.go#L47-L50

**Comment by andrewazores** [comment]
What actually happens nowadays is that the web UI is included, but the jfr-datasource/grafana-dashboard components aren't deployed.

**Comment by ebaron** [comment]
README's See Also section should be updated as well.

**Comment by andrewazores** [comment]
I think the old minimal mode idea, where a user might deploy a Cryostat container alone without even the web-client assets bundled (no jfr-datasource/grafana and no reports sidecars) is pretty much dead at this point, so redefining "minimal" within the Operator context to mean "Cryostat container only, no jfr-datasource/grafana" makes sense. If that's the case then over in the main Cryostat project I think we should rename the "minimal" builds to something else and avoid the confusion so the term isn't overloaded.

Maybe a Cryostat OCI without the web-client assets should be a "headless build"?

**Comment by ebaron** [comment]
"headless" makes sense to me
