### ISSUE TITLE
Rename IMG env var to OPERATOR_IMG

### ISSUE THREAD

**Issue by jan-law** [cryostatio/cryostat-operator#385]
The environment variable used to specify the cryostat operator image in the [Makefile](https://github.com/cryostatio/cryostat-operator/blob/main/Makefile#L24) is named `IMG`. Since the Makefile uses environment variables for several different container images (e.g. `CORE_IMG`, `DATASOURCE_IMG`), renaming this environment variable would help to identify the operator image when running build commands.

**Comment by divyakelaskar** [comment]
I would like to work on this.
