### ISSUE TITLE
Add Grafana Secret to CRD Status

### ISSUE THREAD

**Issue by ebaron** [cryostatio/cryostat-operator#391]
I think it would be useful to add a reference to the Grafana Secret in the Cryostat CR. This would make it easier for a user to locate the the generated Grafana credentials.

**Comment by maxcao13** [comment]
Hi @ebaron, first time on operator, is there a place where I can sort of get started and get more comfortable?

**Comment by ebaron** [comment]
Hey @maxcao13! Would this Operator SDK documentation be useful? It can help explain how the operator is structured: https://sdk.operatorframework.io/docs/building-operators/golang/

There is also some good documentation on Kubebuilder, which the Operator SDK is based on here: https://book.kubebuilder.io/

If this isn't what you had in mind, please let me know. @tthvo, you might find these resources useful as well.
