### ISSUE TITLE
Release Cryostat 2.1 on OperatorHub.io

### ISSUE THREAD

**Issue by jan-law** [cryostatio/cryostat-operator#396]
Now that the 2.1 upstream release is available (see [github tags](https://github.com/cryostatio/cryostat-operator/tags)), Cryostat 2.1 can be released on OperatorHub. Similar to the [2.0 release](https://github.com/k8s-operatorhub/community-operators/pull/481), you'll need to complete the [prerequisites](https://k8s-operatorhub.github.io/community-operators/contributing-prerequisites/) and [open a PR](https://k8s-operatorhub.github.io/community-operators/operator-version-update/) with the updated operator. 

To speed up the approval process, you can also run the operator pre-submission tests as explained [here](https://k8s-operatorhub.github.io/community-operators/tests-in-pr/). These tests are identical to the tests that will run when you open the PR. I think this script worked last time for 2.0:

```
# (assuming you have podman already installed)
# setup steps
sudo dnf install ansible
sudo dnf install kubernetes-kubeadm
sudo swapoff -a # [disable swap for kubelet to work](https://stackoverflow.com/a/52196985)
systemctl enable kubelet.service
systemctl start kubelet

# This command will run the test suite. Notice the container tool is Docker:
OPP_CONTAINER_TOOL=docker OPP_AUTO_PACKAGEMANIFEST_CLUSTER_VERSION_LABEL=1 OPP_PRODUCTION_TYPE=k8s \
bash <(curl -sL https://raw.githubusercontent.com/redhat-openshift-ecosystem/community-operators-pipeline/ci/latest/ci/scripts/opp.sh) \
all \
operators/cryostat-operator/2.0.0 \
jan-law/community-operators \
cryostat-operator
```

**Comment by jan-law** [comment]
If the new interns are interested, I was thinking it would be good for them to get involved with the OperatorHub release. Hareet should also be available to help when he gets back on the 26th too

**Comment by ebaron** [comment]
2.1.1 has now been released. Any takers for this?

**Comment by jan-law** [comment]
> 2.1.1 has now been released. Any takers for this?

@tthvo @maxcao13 ?

**Comment by maxcao13** [comment]
Yeah, I want to try this, @tthvo do you want to do it as well? I think we are going to definitely need some guidance.

**Comment by tthvo** [comment]
yeh sounds great! we can both work on this! @maxcao13

**Comment by hareetd** [comment]
Here's the [issue](https://github.com/cryostatio/cryostat-operator/issues/279) for the original release on OperatorHub.io that @jan-law and I worked on. The PR for the release can be found [here](https://github.com/k8s-operatorhub/community-operators/pull/481).

The issue I've linked contains some context to get you started. Much of the discussion on the issue has to do with errors we encountered running Cryostat on Kubernetes (as opposed to OpenShift) that have since been resolved but there is still useful info. regarding the packaging process for the release.

**Comment by maxcao13** [comment]
Me and @tthvo are having some trouble getting the tests through locally. The error we both see is the one shown here http://pastebin.test.redhat.com/1059686

@hareetd and @jan-law helped us through, but we couldn't get past it. Interestingly the tests passed on @hareetd Fedora 36 local with Podman 4, but we have are not sure why it does not work for us. We've tried restarting our computers and docker as well. 

Things we have tried: 

```
sudo dnf install ansible
sudo dnf install kubernetes-kubeadm
sudo swapoff -a
systemctl start docker
systemctl enable kubelet.service
systemctl start kubelet
minikube start --driver=kvm2

OPP_CONTAINER_TOOL=docker OPP_AUTO_PACKAGEMANIFEST_CLUSTER_VERSION_LABEL=1 OPP_PRODUCTION_TYPE=k8s bash <(curl -sL https://raw.githubusercontent.com/redhat-openshift-ecosystem/community-operators-pipeline/ci/latest/ci/scripts/opp.sh) \
all \ 
operators/cryostat-operator/2.1.1 \
maxcao13/community-operators \
cryostat-operator
```
My forked repo and branch is here
https://github.com/maxcao13/community-operators/tree/cryostat-operator

Fedora 35:
Podman version: 3.4.7
Docker version 20.10.17, build 100c701
Minikube version: v1.25.2

**Comment by tthvo** [comment]
It turned out the script skipped the task to create the registry if `kind` is not available on PATH.  We noticed `sudo` seems to run in a different environment as PATH is different and does not include `$HOME/.local/bin` so `kind` should not be put there.

https://github.com/redhat-openshift-ecosystem/operator-test-playbooks/blob/master/upstream/roles/reset_kind/tasks/reset.yml

Also, running `kind` v0.12.0` appears to cause:

```
TASK [reset_kind : Configuring Kind with registry] **********************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "/tmp/kind-with-registry.sh", "delta": "0:00:31.701774", "end": "2022-06-20 20:06:53.879448", "msg": "non-zero return code", "rc": 1, "start": "2022-06-20 20:06:22.177674", "stderr": "Error: No such container: kind-registry\nCreating cluster \"operator-test\" ...\n • Ensuring node image (kindest/node:v1.21.1) 🖼  ...\n ✓ Ensuring node image (kindest/node:v1.21.1) 🖼\n • Preparing nodes 📦   ...\n ✗ Preparing nodes 📦 \nERROR: failed to create cluster: could not find a log line that matches \"Reached target .Multi-User System.|detected cgroup v1\"", "stderr_lines": ["Error: No such container: kind-registry", "Creating cluster \"operator-test\" ...", "
```

So, we downgraded `kind` to `v0.11.0` as suggested here. 

https://github.com/kubernetes-sigs/kind/issues/2460

**Comment by tthvo** [comment]
Our previous on OperatorHub :))

![Screenshot from 2022-06-21 11-22-27](https://user-images.githubusercontent.com/68053619/174844476-aac71a46-aee2-4071-ad1d-f1b936962ea9.png)

**Comment by tthvo** [comment]
Did we miss anyone?

```
---
updateGraph: semver-mode
reviewers:
 - ebaron
 - andrewazores
 - hareetd
 - jan-law
 - jiekang
 - maxcao123
 - tthvo
```

**Comment by jan-law** [comment]
> @hareetd @jan-law Do we also have to run OpenShift tests [outlined here? ](https://github.com/operator-framework/community-operators/blob/master/docs/testing-operators.md#testing-operator-deployment-on-openshift)

This release for OperatorHub.io is just for kubernetes users I think. I just checked the OpenShift operator catalog and the 2.1.1 release is already there. 

> Did we miss anyone?

Looks good to me!

**Comment by jan-law** [comment]
> Our preview on OperatorHub :))

@ebaron it looks like the example Flight Recording and Recording CRDs (custom resource definitions) are still visible on the preview. I thought those were deprecated?

**Comment by maxcao13** [comment]
### Full steps for passing all OperatorHub tests

On Fedora 35:

Have **kind v0.11.0** in $PATH (we had it as /usr/local/bin/kind)
Have **Podman (v3.4.7)**

```
sudo dnf install ansible #(v.2.9.27)
sudo dnf install kubernetes-kubeadm #(GitVersion:"v1.22.7")
systemctl start docker #(v.20.10.17)
sudo swapoff -a 
systemctl enable kubelet.service #(Kubernetes v1.22.7)
systemctl start kubelet
```
If OLM resource error occurs, use 
`/tmp/operator-test/operator-sdk olm uninstall`

To clean sources run
`bash <(curl -sL https://raw.githubusercontent.com/redhat-openshift-ecosystem/community-operators-pipeline/ci/latest/ci/scripts/opp.sh) clean`

```
Removing testing container 'op-test' ...
Removing kind registry 'kind-registry' ...
Deleting cluster "operator-test" ...
Removing cert dir '/home/mcao/.optest/certs' ..
```
Run test suites:
```
OPP_CONTAINER_TOOL=docker OPP_AUTO_PACKAGEMANIFEST_CLUSTER_VERSION_LABEL=1 OPP_PRODUCTION_TYPE=k8s bash <(curl -sL https://raw.githubusercontent.com/redhat-openshift-ecosystem/community-operators-pipeline/ci/latest/ci/scripts/opp.sh) \
all \ 
operators/cryostat-operator/2.1.1 \
maxcao13/community-operators \
cryostat-operator
```

**Comment by tthvo** [comment]
@jan-law @hareetd We have some questions while going through the PR template.

> Example templates for all Custom Resource Definitions intended to be used

This question, we need to wait for Elliott as [here](https://github.com/cryostatio/cryostat-operator/issues/396#issuecomment-1161959398)

> Is your new CSV referenced in the [appropriate channel](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#channels) defined in the `package.yaml` or `annotations.yaml` ?

We are not sure we understand this and how to check if valid?

**Comment by ebaron** [comment]
> > Our preview on OperatorHub :))
> 
> @ebaron it looks like the example Flight Recording and Recording CRDs (custom resource definitions) are still visible on the preview. I thought those were deprecated?

That's right. They're deprecated and we use the `operators.operatorframework.io/internal-objects` annotation to hide them from view in the OpenShift Console. It appears that OperatorHub.io doesn't support this annotation yet though: https://github.com/k8s-operatorhub/operatorhub.io/issues/14.

Users will see warnings about those types being deprecated when using them on the command line at least.

**Comment by ebaron** [comment]
> > Is your new CSV referenced in the [appropriate channel](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#channels) defined in the `package.yaml` or `annotations.yaml` ?
> 
> We are not sure we understand this and how to check if valid?

All of our operator releases should use the `stable` channel going forward. This is because we only want to support the latest release. The head of the `stable` channel will always contain the latest released version of our operator.

`package.yaml` seems to refer to the old `packagemanifests` format, so you don't need to worry about that.

`annotations.yaml` is what we use with the `bundle` format. For the 2.1.1 release, that would be this file: https://github.com/cryostatio/cryostat-operator/blob/v2.1.1/bundle/metadata/annotations.yaml. The `stable` channel is listed as the only channel, and also the default:
https://github.com/cryostatio/cryostat-operator/blob/88ee94131b1fcbf5a3587f06822cfd9de45732ac/bundle/metadata/annotations.yaml#L7-L8

I think in our case, we just have to ensure that the channels listed in `annotations.yaml` are what we expect them to be.

**Comment by ebaron** [comment]
> Full steps for passing all OperatorHub tests

Thanks @maxcao13! This will be a very useful resource when we need to do our next release.

**Comment by ebaron** [comment]
> Did we miss anyone?
> 
> ```
> ---
> updateGraph: semver-mode
> reviewers:
>  - ebaron
>  - andrewazores
>  - hareetd
>  - jan-law
>  - jiekang
>  - maxcao13
>  - tthvo
> ```

Looks good!

**Comment by tthvo** [comment]
Thanks @ebaron we will open the PR in a few minutes and send the link here

**Comment by ebaron** [comment]
It's showing up here now: https://operatorhub.io/operator/cryostat-operator

Thanks for doing this!
