### ISSUE TITLE
Add default resource requests for Cryostat containers

### ISSUE THREAD

**Issue by ebaron** [cryostatio/cryostat-operator#406]
While we allow the user to specify resource requirements for each Cryostat container, we currently default to no requirements. To follow operator best practices, we should at least provide default CPU/memory requests for each container [1].

[1] https://sdk.operatorframework.io/docs/best-practices/managing-resources/

**Comment by ebaron** [comment]
We will need to consider what we be good defaults.

**Comment by tthvo** [comment]
@ebaron Can we use the numbers in these examples for default? Or are they just for pure examples?

https://github.com/cryostatio/cryostat-operator/blob/main/docs/config.md#resource-requirements

**Comment by ebaron** [comment]
I think most of these were arbitrarily chosen. 768MiB is probably good for Cryostat itself. @andrewazores do you have any suggestions on default resource requests for the each of the operand containers? We can skip setting default limits for now, but requests are considered mandatory.

**Comment by andrewazores** [comment]
Not really. We should probably do a bit of profiling to find out what kind of requirements the Grafana dashboard really has. jfr-datasource shouldn't need too much, though it does need to be able to load and parse JFR files, so the memory requirement there probably scales with the average size of recording a user is inspecting - much like for `-reports`.

**Comment by tthvo** [comment]
> Not really. We should probably do a bit of profiling to find out what kind of requirements the Grafana dashboard really has. jfr-datasource shouldn't need too much, though it does need to be able to load and parse JFR files, so the memory requirement there probably scales with the average size of recording a user is inspecting - much like for `-reports`.

@andrewazores What would be the average size for the recording?

**Comment by andrewazores** [comment]
> What would be the average size for the recording?

That's an unanswerable question - it depends entirely on the end user and how they're using Cryostat. How long they run recordings for and how many events they capture.

How long is a piece of string?

In our development testing deployments we usually only deal with recordings on the scale of megabytes to tens of megabytes, but that isn't necessarily representative.

> Edit 0: I will try the 450mb jfr file for testing. Maybe larger? Or is 450mb too large?
> Edit 1: 450mb appears to give 500 status due to 29s timeout. Maybe we expect the average to be < 450mb?

450MB is a pretty big file, so to process it in under 29 seconds could take a lot of resources. A user dealing with 450MB average filesizes is going to have vastly higher baseline resource requirements than a user dealing with 4.5MB average filesizes, and especially so if they want processing to finish in a timely manner.

Anyway, your profiling steps make sense and look good to me. I would suggest modifying the Cryostat CR and adding a `cryostat-reports` replica, and checking the resource requirement there when you "View Report" on such a large recording that way too.

**Comment by tthvo** [comment]
> That's an unanswerable question - it depends entirely on the end user and how they're using Cryostat. How long they run recordings for and how many events they capture.

Ahhh I was thinking of something like a common use case. But i guess its not practical then. Then, any way to check what a resource request should be?

> Anyway, your profiling steps make sense and look good to me. I would suggest modifying the Cryostat CR and adding a cryostat-reports replica, and checking the resource requirement there when you "View Report" on such a large recording that way too.

Ohh yess I will do that!

**Comment by ebaron** [comment]
> > That's an unanswerable question - it depends entirely on the end user and how they're using Cryostat. How long they run recordings for and how many events they capture.
> 
> Ahhh I was thinking of something like a common use case. But i guess its not practical then. Then, any way to check what a resource request should be?

I think we might have to be a bit arbitrary then. Perhaps taking a 10-20 minute Profiling recording as a baseline. Of course, this should be from an application that's actually doing something during this time. Maybe the vertx-fib-demo is enough, I'm not sure. Then see what the maximum memory usage is when processing that recording in JFR Data Source and the reports generator.

Since we're only setting resource requests, containers can use additional resources if they're available on the node. This can still backfire because setting the requests too low means that our pod could get scheduled on a node with few available resources.

**Comment by andrewazores** [comment]
Yep, whatever we do here is a "best effort heuristic". Provisioning resources to suit a 10-20 minute Profiling run sounds reasonable, but for users that only ever do 30 second Continuous monitoring runs, the defaults we supply are probably way over-provisioned.

Using `vertx-fib-demo` as a test case baseline should be fairly reasonable, if not a little on the low side since it's quite simple compared to any real production application. Just be sure to actually visit its web page and set it to perform some Fibonacci calculations, otherwise it only sits there idling.

**Comment by tthvo** [comment]
After starting a 15min recording on `vertx-fib-demo` (running fib calculations most of the times):

**Opening View Report**:
```
POD                                                     NAME                             CPU(cores)   MEMORY(bytes)   
cryostat-sample-reports-797f8bf98c-72q4g                POD                              0m           0Mi             
cryostat-sample-reports-797f8bf98c-72q4g                cryostat-sample-reports          1m           211Mi             
```
**Opening View In Grafana**:
```
POD                                                     NAME                             CPU(cores)   MEMORY(bytes)    
cryostat-sample-646d899d6f-zcfvt                        cryostat-sample-grafana          2m           67Mi            
cryostat-sample-646d899d6f-zcfvt                        cryostat-sample-jfr-datasource   19m          224Mi           
cryostat-sample-reports-797f8bf98c-72q4g                POD                              0m           0Mi             
cryostat-sample-reports-797f8bf98c-72q4g                cryostat-sample-reports          1m           223Mi                   
```
Might need to run a couple more times. But any thoughts on the values for requests @ebaron @andrewazores ?

**Comment by ebaron** [comment]
Hmm, that's a bit more than I was expecting for a 3.4MB JFR file, especially for jfr-datasource since that should be a native image. @tthvo would it be much trouble to try a 30min recording of the same and seeing how that compares in terms of JFR file size and memory usage?

**Comment by tthvo** [comment]
yahh sure @ebaron I already have them setup so I just have run :D will give updates when done!

**Comment by tthvo** [comment]
@ebaron Here are the new metrics with a Profiling recording for 30min (54.0MB)

**After successfully upload jfr**:
```
POD                                                     NAME                             CPU(cores)   MEMORY(bytes)   
cryostat-sample-646d899d6f-j7s27                        cryostat-sample-grafana          0m           68Mi            
cryostat-sample-646d899d6f-j7s27                        cryostat-sample-jfr-datasource   1m           886Mi           
cryostat-sample-reports-797f8bf98c-hskqf                cryostat-sample-reports          1m           172Mi                 
```

**Openning Grafana Dashboard**
```
POD                                                     NAME                             CPU(cores)   MEMORY(bytes)   
cryostat-sample-646d899d6f-j7s27                        cryostat-sample-grafana          5m           68Mi            
cryostat-sample-646d899d6f-j7s27                        cryostat-sample-jfr-datasource   29m          1667Mi          
cryostat-sample-reports-797f8bf98c-hskqf                cryostat-sample-reports          1m           173Mi                   
```

This is the first run. I tried again and noticed jfr-datasource increases cpu usage much more while in dashboard. Not sure why.

**Comment by tthvo** [comment]
The high memory usage of datasource, I guess, is due to jfr data converted to grafana-compatible form being held in memory?

**Comment by ebaron** [comment]
Wow, that's quite the jump in JFR file size and memory usage. Based on these results, I'm leaning towards just choosing 512MiB requests for jfr-datasource and cryostat-reports. 256MiB is probably not enough, but 1GiB seems like asking too much by default. @andrewazores what do you think?

**Comment by ebaron** [comment]
> The high memory usage of datasource, I guess, is due to jfr data converted to grafana-compatible form being held in memory?

I believe so

**Comment by tthvo** [comment]
Also how about cpu usage? I guess datasource is the main concern seems it scales fast with jfr size?

**Comment by ebaron** [comment]
> Also how about cpu usage? I guess datasource is the main concern seems it scales fast with jfr size?

Maybe 20m for each based on these results? I'm a bit surprised the report generation is so light on CPU usage for larger recordings.

**Comment by tthvo** [comment]
> I'm a bit surprised the report generation is so light on CPU usage for larger recordings.

@ebaron Ahh sorry I didnt include metrics for opening reports. Here it is. Above I break the second step (opening Grafana) into 2 small steps (upload and dashboard).

**Opening View Report:**:
```
POD                                                     NAME                             CPU(cores)   MEMORY(bytes)           
cryostat-sample-reports-797f8bf98c-rmfvv                POD                              0m           0Mi             
cryostat-sample-reports-797f8bf98c-rmfvv                cryostat-sample-reports          775m         1093Mi                    
```

No report was shown as timeout reached.

**Comment by andrewazores** [comment]
Are these tests being run with no container limits? The memory usage could be skewed if so, because the JVM will be willing to grab a lot of memory during peak processing before later running a GC and freeing that memory. I'm pretty sure we have successfully used the Grafana and report generation features on ~50MB JFR files before without allocating ~1GB of memory to those two containers.

**Comment by tthvo** [comment]
> Are these tests being run with no container limits?

@andrewazores sorry how do I check this? I did `oc describe` on cryostat and report. I don't see any resource request/limit. Is this the way?

**Comment by tthvo** [comment]
Also, just a quick notice. While being idle after opening the report for 54MB jfr, the report container state:

```
POD                                                     NAME                             CPU(cores)   MEMORY(bytes)                          
cryostat-sample-reports-797f8bf98c-2st7m                cryostat-sample-reports          1m           1040Mi 
```
Are resources not cleaned up tho?

**Comment by andrewazores** [comment]
> > Are these tests being run with no container limits?
> 
> @andrewazores sorry how do I check this? I did `oc describe` on cryostat and report. I don't see any resource request/limit. Is this the way?

I think so, but I haven't looked at this myself in a while.

> Are resources not cleaned up tho?

It should be, eventually. The reports container just does its processing work and sends the response back over HTTP, nothing should be cached or otherwise retained. I would expect the GC to have run at some point and cleaned that up, but perhaps not (yet). It's also possible that the way Java allocations memory and the way OpenShift counts memory leads to misleading readouts. For example, it could be the case that the JVM sees a lot of available memory, so it allocates large chunks and internally the JVM runtime uses this for buffers and things as needed, without releasing it back to the OS until there is memory pressure to do so. That memory wouldn't actually always be in use by the Java program, but it is allocated by the process and not freed. This would be a similar scenario to https://www.linuxatemyram.com/ .

To really know what's going on inside, we could use JFR to profile the reports container... !

We build and deploy `jfr-datasource` as a native image so we can't hook it up to Cryostat to pull JFR data out for profiling, so we'll need to figure out something else.

**Comment by tthvo** [comment]
Ahh understood :D Any thoughts on this issue? Since it is possible

> the way OpenShift counts memory leads to misleading readouts.

How reliable are the results of `oc adm top` tho? I guess we need to run these checks again and multiple times. Any better ideas?

**Comment by tthvo** [comment]
Hmm I will try to see how I would start the profiling and get these metrics as you suggested. Will updates here with new metrics :D

**Comment by tthvo** [comment]
## Setup
- All below runs are checked against the `vertx-fib-demo` container.
- All metrics are taken as max during "working" period.
- All metrics are taken from Openshift Platform Metric Dashboard.
- When metrics are taken:
  - **_Core metric:_** while doing recording.
  - **_Datasource metric:_** uploading jfr, setting jfr data and serving for grafana.
  - **_Grafana metric:_** interacting with dashboard.
  - **_Report metric:_** openning report view.

### Results

All checks run on cluster-bot (Openshift 4.10.18).

### 15-min Profiling

| NAME  | CPU (core) | MEMORY (MiB) |
| ----- | ---------- | ------------ |
| core            | 0.067  | 337.3MiB  |
| jfr-datasource  | 0.184  | 674.9MiB | 
| cryostat-grafana-dashboard  | 0.009 | 51.56MiB |
| cryostat-reports | 0.564 | 715.4 MiB |


### 30-min Profiling

| NAME  | CPU (core) | MEMORY (MiB) |
| ----- | ---------- | ------------ |
| core            | 0.07  | 343.2MiB  |
| jfr-datasource  | 0.175  | 672.9MiB | 
| cryostat-grafana-dashboard  | 0.008 | 62.34MiB |
| cryostat-reports | 0.728 | 714 MiB |

### 30-min Profiling (with datasource in JVM and JMX-enabled reports)

| NAME  | CPU (core) | MEMORY (MiB) |
| ----- | ---------- | ------------ |
| core            | 0.065  | 315.2MiB  |
| jfr-datasource  | 0.285  | 1.1GiB | 
| cryostat-grafana-dashboard  | 0.006 | 40.89MiB |
| cryostat-reports | 0.866 | 2.47GiB |

Datasource image (JVM): `quay.io/thvo/jfr-datasource:latest`
Report with JMX-enabled (JVM): `quay.io/thvo/cryostat-reports:latest`  (have to modify operator to set jmx port in report's service).

**Metric Screenshots**

[metric_screenshots.zip](https://github.com/cryostatio/cryostat-operator/files/9294780/metric_screenshots.zip)

**JFRs (Report & Datasource)**
[jfr.zip](https://github.com/cryostatio/cryostat-operator/files/9294786/jfr.zip)

**Comment by tthvo** [comment]
I am thinking based on these 30-min baseline.

**Core:**
- Request.Cpu: `100m`
- Request.Memory: `384MiB` (half of the recommended limit we suggest in docs)

**Grafana:** It appears to consume little, but we should stick with [Grafana Doc](https://grafana.com/docs/grafana/latest/setup-grafana/installation/#hardware-recommendations)?
- Request.Cpu: `1000m`
- Request.Memory: `255MB`

**Datasource:** It appears not so cpu intensive but requires lots of memory for storing datasource.
- Request.Cpu: `300m`
- Request.Memory: `1024MiB`

**Report:** I guess this requires more processing and memory. Not sure about this?
- Request.Cpu: `1000m`
- Request.Memory: `768MiB`

Any thoughts @andrewazores @ebaron?

**Comment by andrewazores** [comment]
Those measurements/suggestions for the main Cryostat container and the Grafana Dashboard make sense. -reports and especially jfr-datasource will scale up their resource usage along with the size of the input file, so I think we can start with a lower baseline recommendation at minimum.

If we can establish even a very approximate heuristic for `jfr file size -> memory usage ` for both of those containers as well as the minimum recommendation that would be awesome.

**Comment by andrewazores** [comment]
You could use `cryostat-reports` itself as the JVM under test while doing that, too. It's a more realistic test case than `vertx-fib-demo` is. Just be sure to actually ask it to produce some reports during the recordings. Preferably, use a consistent input file each time, and perform the requests at a regular interval. This way the recording size and length should be about linearly correlated.

ie take a manual recording of `vertx-fib-demo` while you hammer it with some requests for "large" Fibonacci numbers over a few minutes. Then download that recording. Start a Profiling recording on `cryostat-reports` and request it to process the original recording taken from `vertx-fib-demo`. Download that recording file and stop the active recording. Restart the recording and send a new request to `cryostat-reports` to process the recording you just took from it, then send an identical request again 30 seconds later, and another 30 seconds later, etc. until the total duration has reached your 1/2/5/10/15/20/30/60 minute mark.

**Comment by tthvo** [comment]
Looks like I can use Openshift Metrics Dashboard to check container resource usage. This way we can check native image too. I will try to get recordings from increasing size for `vertx` while hammering with large sequence. Then, repeatedly load them in datasource or send to report. Might not be ideal but should give us a rough idea on this approximate heuristic in this tight timeframe.
