### ISSUE TITLE
Service account token secret name not found

### ISSUE THREAD

**Issue by tthvo** [cryostatio/cryostat-operator#426]
Service account token secret names are prefixed with `cryostat-operator-service-account-token-*` but in README, the guide show secret name prefixed with `cryostat-operator-token-*`.

https://github.com/cryostatio/cryostat-operator/blob/5212264d9c61007472ddb599d042b665f8b4a3b9/README.md?plain=1#L130

Output of getting secrets:
```
$ oc get secrets
NAME                                                TYPE                                  DATA   AGE
builder-dockercfg-dlp2p                             kubernetes.io/dockercfg               1      74d
builder-token-lvv5f                                 kubernetes.io/service-account-token   4      74d
builder-token-txj4p                                 kubernetes.io/service-account-token   4      74d
cryostat-operator-service-account-dockercfg-gj2rr   kubernetes.io/dockercfg               1      39m
cryostat-operator-service-account-dockercfg-w2qmr   kubernetes.io/dockercfg               1      39m
cryostat-operator-service-account-token-7tt7l       kubernetes.io/service-account-token   4      39m
cryostat-operator-service-account-token-dwmnk       kubernetes.io/service-account-token   4      39m
cryostat-operator-service-account-token-kt4xt       kubernetes.io/service-account-token   4      39m
default-dockercfg-rbltp                             kubernetes.io/dockercfg               1      74d
default-token-96bq2                                 kubernetes.io/service-account-token   4      74d
default-token-ntc9j                                 kubernetes.io/service-account-token   4      74d
deployer-dockercfg-js7jl                            kubernetes.io/dockercfg               1      74d
deployer-token-dxj9t                                kubernetes.io/service-account-token   4      74d
deployer-token-qpzdj                                kubernetes.io/service-account-token   4      74d
```

**Comment by ebaron** [comment]
Hi @tthvo, good job noticing this. I think this whole section is out-of-date. Currently the operator only sets up authentication when running on OpenShift. Now we have OAuth integration, so the user can authenticate just as they would with the OpenShift console or other OpenShift OAuth applications.

**Comment by tthvo** [comment]
So would we remove this section since it is no longer in use? Or maybe some sort of warning?

**Comment by ebaron** [comment]
Oh wait, line 122 mentions the OAuth login flow.
https://github.com/cryostatio/cryostat-operator/blob/5212264d9c61007472ddb599d042b665f8b4a3b9/README.md?plain=1#L122

As long as that is present, we could just update the secret name as you suggested. I think this section could use a rewrite overall, but for now the easiest thing to do is fix the secret name.

**Comment by tthvo** [comment]
Suree I will just update the secret name for now!
