### ISSUE TITLE
go-get-tool should install to $1 instead of $PROJECT_DIR/bin

### ISSUE THREAD

**Issue by tthvo** [cryostatio/cryostat-operator#431]
> go-get-tool will 'go get' any package $2 and install it to $1.

`go-get-tool` defined in Makefile said to install the path specified in `$1` but eventually installs to `$PROJECT_DIR/bin` anyaway.

https://github.com/cryostatio/cryostat-operator/blob/5ceb7db194b765c07bf1e9270ea248da16cae581/Makefile#L224

**Comment by tthvo** [comment]
Also should we use `go install` instead of `go get` as it is deprecated? 

Any thoughts @ebaron @andrewazores?

**Comment by tthvo** [comment]
Trying to reuse this method to fetch `setup-envtest` binary since new updates in `controller-runtime 0.10.0` removes `hack/setup-envtest.sh` so this 

https://raw.githubusercontent.com/kubernetes-sigs/controller-runtime/v0.10.0/hack/setup-envtest.sh

is not valid anymore. 

See #430

**Comment by ebaron** [comment]
> 

I think so. This would be required in order to work with Golang >= 1.18. Ideally, this would also work with 1.16, which I think it does.

**Comment by ebaron** [comment]
> Trying to reuse this method to fetch `setup-envtest` binary since new updates in `controller-runtime 0.10.0` removes `hack/setup-envtest.sh` so this
> 
> https://raw.githubusercontent.com/kubernetes-sigs/controller-runtime/v0.10.0/hack/setup-envtest.sh
> 
> is not valid anymore.
> 
> See #430

Something that may be useful is the Operator SDK's project in their `testdata`. This shows what the boilerplate looks like when generated by the newest SDK:

**Comment by tthvo** [comment]
Right! I will try going with their way for setting up env-test and use `go install` while upgrading sdk (will ref this issue there). Thanks @ebaron

**Comment by ebaron** [comment]
Sounds good, you can also change the tag to different SDK releases if you want to see what the Makefile looks like for a particular release, for example.
