### ISSUE TITLE
Allow users to modify the Cryostat permission mapping

### ISSUE THREAD

**Issue by ebaron** [cryostatio/cryostat-operator#439]
It's also possible that the downstream build carries a patch for Operator-supplied CRDs. Or maybe the upstream Operator can even carry its own whole `.properties` file and mount that to the Cryostat container in place of the default upstream one.

_Originally posted by @andrewazores in https://github.com/cryostatio/cryostat/issues/979#issuecomment-1146325376_

One possible solution to this is to add a Config Map reference to the Cryostat CRD. This Config Map would have to contain an properties file compatible with the OpenShiftAuthManager: https://github.com/cryostatio/cryostat/blob/bd95e1a11e9e29cc39559f4a5fdeaae77e81b4c6/src/main/resources/io/cryostat/net/openshift/OpenShiftAuthManager.properties

If provided by the user, the operator could mount this properties file in the correct location for Cryostat to use instead of the default permissions mapping.

**Comment by andrewazores** [comment]
![2022-08-17T15:05:40,055148430-04:00](https://user-images.githubusercontent.com/3787464/185222214-d7873ca9-e4bd-45d2-b55c-17b494786444.png)


The in-container path to the file is `/app/resources/io/cryostat/net/openshift/OpenShiftAuthManager.properties`.
