### ISSUE TITLE
Cryostat should be deployed in `h2:file` mode

### ISSUE THREAD

**Issue by andrewazores** [cryostatio/cryostat-operator#451]
These two environment variables should be set for the Cryostat container:

https://github.com/cryostatio/cryostat/blob/58bc83dd1e0145bf34cd3289f908a929ef664d6a/smoketest.sh#L22

If not set then the container defaults to running in `h2:mem` mode, which does not provide an actual persistent database. The discovery API would be not durable across reboots, which also means custom target definitions would not survive.

**Comment by tthvo** [comment]
What if we allow customization for this behaviour? Maybe a spec field to set which type of storage to use?

Also, just wondering how `postgres` is etup our deployment on k8s/OCP context :D

**Comment by andrewazores** [comment]
Yea, eventually we should make it configurable. Right now the change is too fresh and likely to change heavily for the next release too so I don't want to try to support a Postgres setup in the official distribution just yet.

I guess if the Cryostat CR has no storage allocated (no PVC), then the Operator could automatically configure Cryostat to use `h2:mem`. If there is a PVC then use `h2:file` with the file located somewhere on that PVC.
