### ISSUE TITLE
Add CR property to disable Cryostat built-in discovery mechanisms

### ISSUE THREAD

**Issue by andrewazores** [cryostatio/cryostat-operator#452]
The environment variable `CRYOSTAT_DISABLE_BUILTIN_DISCOVERY` can be set to `true` on the Cryostat container to disable the built-in discovery mechanisms. In an Operator context this would mean disabling Cryostat's `Endpoints` querying/watch. This would be used in cases where the end user only intends to have applications discovered via the Discovery Plugin API.

**Comment by tthvo** [comment]
@andrewazores  I just noticed that Cryostat check the presence/non-blankness of the variable to determine whether to disable built-in discovery.

https://github.com/cryostatio/cryostat/blob/bc9eb4d2319eb8e2b340eca6090fdc41c176e162/src/main/java/io/cryostat/discovery/BuiltInDiscovery.java#L82

Should this condition also includes a check for its value? If not, the operator can just not mount the environment in if disabled option is chosen.

**Comment by andrewazores** [comment]
It could be a check for the value, sure. But I think in a few different places Cryostat just does what you see there and checks whether the variable is defined/non-empty, rather than checking for a specific `"true"` string.

Is how it works now easy enough to deal with on the Operator side?

**Comment by tthvo** [comment]
Right, it would not be a problem :D Operator could check and not mount the environment easy enough.
