### ISSUE TITLE
Delete Grafana certificate and secret when in minimal mode

### ISSUE THREAD

**Issue by ebaron** [cryostatio/cryostat-operator#471]
The Grafana certificate and associated secret do not need to be around when running in the minimal configuration. We should not create the certificate and delete it if it exists. In most cases, the secret should be garbage collected, but there's a possibility we delete the certificate before adding an owner reference to the secret created by cert-manager.

**Comment by jaadbarg** [comment]
@ebaron I'd like to take this one

**Comment by ebaron** [comment]
This certificate creation code resides here: https://github.com/cryostatio/cryostat-operator/blob/119a5f76c14f491ad57b707c01b917830a24e813/internal/controllers/certmanager.go#L106-L111

We should add a condition here that only creates the certificate when `cr.Spec.Minimal` is false. When true, it instead deletes the certificate and secret, if they exist. You can obtain the secret for a certificate (if it exists yet) using the `r.GetCertficateSecret` method. There is a `r.deleteSecret` method already which should be useful, you'll need to add one that is similar for certificates as well.
