### ISSUE TITLE
Add a Scorecard test that manages recordings

### ISSUE THREAD

**Issue by ebaron** [cryostatio/cryostat-operator#504]
A good end-to-end test would involve creating a recording using Cryostat's HTTP API, and then performing some actions on it: e.g. get, archive, generate report, delete.

**Comment by ebaron** [comment]
This would build off the existing Cryostat CR Test: https://github.com/cryostatio/cryostat-operator/blob/a05b5173b4306aacb90eb82ee14ef017b3c6e05a/internal/test/scorecard/tests.go#L71

We would reuse the process of creating a Cryostat CR and waiting for the deployment to become available, but go beyond that to exercise Cryostat's HTTP API. This could involve listing targets, creating a recording, fetching the recording, etc.. We could build off this further in the future. To begin with, we could use Cryostat itself as a target.

Golang has a nice built-in HTTP client library that can be used for interacting with Cryostat's HTTP server:
https://gobyexample.com/http-client

**Comment by tthvo** [comment]
Hi @ebaron, I just have a question about authentication for API requests to Cryostat. I wonder whether we should disable auth? For k8s, right now, there is no auth. For OCP, I am thinking of using a custom mapping to empty lists (not sure if that works as "allowing" everything").

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-properties
data:  
  auth.properties: |
    TARGET=
    RECORDING=
    CERTIFICATE=
    CREDENTIALS=
```

Or do you have any guides on this matter?

**Comment by tthvo** [comment]
Otherwise, I am thinking of either waiting for #206 to use basic auth or in a way (i.e. secret), pass in a valid oauth token (probably use kubeadmin) to scorecard pod. I am not sure how to generate one within the scorecard pod...

**Comment by ebaron** [comment]
Hey @tthvo, good question! Could we use the the Scorecard pod's service account token as Bearer authentication on OpenShift? We could add any permissions we need for the default authz mapping here: https://github.com/cryostatio/cryostat-operator/blob/main/internal/images/custom-scorecard-tests/rbac/scorecard_role.yaml

**Comment by ebaron** [comment]
Kubernetes client-go's `rest.InClusterConfig()` function should give us the bearer token:
https://github.com/kubernetes/client-go/blob/84a6fe7e4032ae1b8bc03b5208e771c5f7103549/rest/config.go#L538

**Comment by tthvo** [comment]
@ebaron Hi, you r right! It turned out pretty nicely with the SA token.

```
Results:
	Name: cryostat-cr
	State: fail

	Errors:
		failed to create a recording: API request failed with status code: 400
	Log:
		
		deployment cryostat-cr-test is not yet available
...output-omitted...
		deployment cryostat-cr-test is not yet available
		deployment cryostat-cr-test is available
		application is ready at https://cryostat-cr-test-cryostat-operator-scorecard.apps-crc.testing
		no target is yet discovered
		found target: {ConnectUrl:service:jmx:rmi:///jndi/rmi://10-217-1-3.cryostat-operator-scorecard.pod:9091/jmxrmi Alias:cryostat-cr-test-7bfdf958bd-mjcqx}
```

I was able to call v1 api with that token^^ Thankss!!

**Comment by ebaron** [comment]
Awesome, thanks @tthvo!
