### ISSUE TITLE
[Request] Replace GHCR_PR_TOKEN with GITHUB_TOKEN

### ISSUE THREAD

**Issue by tthvo** [cryostatio/cryostat-operator#613]
### Describe the feature

Since the event is `pull_request_target`, the `GITHUB_TOKEN` is allowed to elevate its permission to `write:packages`. We can utilize this instead of the `GHCR_PR_TOKEN` PAT. 

Tho, we will need to make sure to specify only necessary permissions.

### Anything other information?

https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token

**Comment by andrewazores** [comment]
Need to double check the permission elevation thing. It may work here since the event is `pull_request_target` as opposed to a comment, but: https://github.com/cryostatio/cryostat/pull/1631#issuecomment-1692439904

**Comment by tthvo** [comment]
Source: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token

>  If the default permissions for the GITHUB_TOKEN are restrictive, you may have to elevate the permissions to allow some actions and commands to run successfully.

Right! Permissions need to be explicitly elevated.

**Comment by tthvo** [comment]
Hmm actually, these should be the steps to take?

https://docs.github.com/en/packages/managing-github-packages-using-github-actions-workflows/publishing-and-installing-a-package-with-github-actions#upgrading-a-workflow-that-accesses-a-registry-using-a-personal-access-token

**Comment by tthvo** [comment]
ping @aali309
