### ISSUE TITLE
Release Operator 2.3.1 on OperatorHub.io

### ISSUE THREAD

**Issue by mwangggg** [cryostatio/cryostat-operator#623]
reference: #585

**Comment by tthvo** [comment]
Release is up: https://operatorhub.io/operator/cryostat-operator

Seems like on the k8s-community repo, the person to `/unhold` has to be the one to also approve. Not sure but worth adding to knowledge hub.

I think we can close this?

**Comment by andrewazores** [comment]
Done: https://github.com/k8s-operatorhub/community-operators/pull/3221
