### ISSUE TITLE
[Task] Update CI badge

### ISSUE THREAD

**Issue by tthvo** [cryostatio/cryostat-operator#631]
After #619, the CI badge is broken.

![image](https://github.com/cryostatio/cryostat-operator/assets/68053619/824e60f5-82ce-4766-90f0-dcefbfcdc50a)

**Comment by tthvo** [comment]
Now that test and quay push are separated. We should have 2 badges for test and push (i.e. basically a link to the quay image).

Something like https://github.com/quarkusio/quarkus. They have a badge for maven artifacts. We can explore an option for quay image.

**Comment by 733amir** [comment]
@tthvo We only need to update the link from `ci.yml` to `build-ci.yml`? 🤔

**Comment by tthvo** [comment]
Right! We also want to have the test status. That should be `test-ci-push.yaml`
