### ISSUE TITLE
[Request] Makefile should have short summaries for targets

### ISSUE THREAD

**Issue by tthvo** [cryostatio/cryostat-operator#634]
### Describe the feature

This would be helpful to contributors to not have to check the Makefile:

```
$ make help
Usage:
  make <target>
  help             Display this help.
  oci-buildx       Build OCI image for the manager for cross-platform support
  operator-sdk     Download operator-sdk locally if necessary.
```

### Anything other information?

Operator-sdk scaffold sets this up so we can sync with them.

https://github.com/operator-framework/operator-sdk/blob/e67da35ef4fff3e471a208904b2a142b27ae32b1/testdata/go/v3/memcached-operator/Makefile#L86

Each target needs trailing comments on target definition line, for example:

https://github.com/operator-framework/operator-sdk/blob/e67da35ef4fff3e471a208904b2a142b27ae32b1/testdata/go/v3/memcached-operator/Makefile#L93

**Comment by pektezol** [comment]
Do you only need this for oci-buildx and operator-sdk or all targets?

Also I couldn't see a operator-sdk target, am I looking wrong

**Comment by tthvo** [comment]
Hi @pektezol, we will need this for all targets. The `operator-sdk` is not yet available on `main`. I took the example from #629.

**Comment by pektezol** [comment]
Sounds good, @tthvo ! I would like to help with this sometime today.

**Comment by tthvo** [comment]
Thanks!! Appreciate that!

**Comment by pektezol** [comment]
@tthvo is it expected of me to write new summaries for targets that don't have them?

**Comment by tthvo** [comment]
That would be awesome! But pls let me know if you need help.

**Comment by pektezol** [comment]
Let me know if it needs adjusting, since I'm new to this.
