### ISSUE TITLE
[Story] Deploy Cryostat 3.0

### ISSUE THREAD

**Issue by Josh-Matsuoka** [cryostatio/cryostat-operator#710]
### Describe the feature

In line with Helm (https://github.com/cryostatio/cryostat-helm/issues/110) the Operator should be updated to deploy development builds of Cryostat 3.0

This can be roughly broken down into the following sub tasks:

- Deploy Cryostat 3.0 with hardcoded database and storage containers, no auth
- Add in the auth proxy, put storage behind the auth proxy
- Add in grafana, put it behind the auth proxy
- Re-enable basic auth

**Comment by andrewazores** [comment]
Initial round of this is done now. In the future the database and storage containers should be pulled out into their own Pods as well.
