### ISSUE TITLE
[Request] CRD field(s) for configuring Kubernetes API discovery

### ISSUE THREAD

**Issue by andrewazores** [cryostatio/cryostat-operator#714]
### Describe the feature

https://github.com/cryostatio/cryostat/issues/1861

A CRD field(s) should be added to allow the end user to configure the port name(s) and number(s) used for Kubernetes API Endpoints discovery.

It may also be useful to add a field that allows the user to simply turn off Kubernetes API discovery, in case they only want to use custom targets, Cryostat Agent, or custom discovery plugins.

**Comment by ebaron** [comment]
A good place for the field(s) would be the TargetDiscoveryOptions:
https://github.com/cryostatio/cryostat-operator/blob/6ac7ec6aac49f3933b6314227e19b9d64a457b07/api/v1beta1/cryostat_types.go#L521-L527

**Comment by tthvo** [comment]
I can help with this if it's not yet token :))

**Comment by andrewazores** [comment]
Sure, nobody else has claimed it yet :-)
