### ISSUE TITLE
[Story] Remove Minimal mode

### ISSUE THREAD

**Issue by ebaron** [cryostatio/cryostat-operator#728]
I'm in favour of removing the `minimal` config option: https://github.com/cryostatio/cryostat-helm/pull/122

_Originally posted by @andrewazores in https://github.com/cryostatio/cryostat-operator/pull/721#discussion_r1486338493_

**Comment by tthvo** [comment]
This is for 2.x release right? I can help with this :D

**Comment by ebaron** [comment]
Hi @tthvo this is for 3.0.0. So it should target the `cryostat3` branch.

**Comment by tthvo** [comment]
ohhh sounds good! But I can still help with it, I think :)))

**Comment by tthvo** [comment]
Hi @ebaron, should I take on this?

**Comment by ebaron** [comment]
> Hi @ebaron, should I take on this?

That would be great if you have time! Just target the `cryostat3` branch instead of `main` for the feature branch.

**Comment by tthvo** [comment]
Sure thanks! I will do that!

**Comment by ebaron** [comment]
Also, just to be clear, this should be removed from the v1beta2 API but not in v1beta1. The new conversion webhook can just ignore whatever the minimal value of a v1beta1 CR when converting to v1beta2. Likewise, when converting from v1beta2 to v1beta1, we can default it to false.
