### ISSUE TITLE
[Epic] Breaking CRD changes for 3.0

### ISSUE THREAD

**Issue by ebaron** [cryostatio/cryostat-operator#731]
Some CRD options no longer make sense for Cryostat 3.0. These include:
- [x] #728 
- [x] #729
- [x] #730
- [x] #732

**Comment by tthvo** [comment]
Hey @ebaron, is there any planned for 3.0 tasks that I can help you here?

**Comment by ebaron** [comment]
> Hey @ebaron, is there any planned for 3.0 tasks that I can help you here?

Hey @tthvo, I think there may be some additional breaking changes that will follow #710. Some things we discussed were [removing parts or all](https://github.com/cryostatio/cryostat-operator/pull/727#discussion_r1543160227) of the Authorization Properties as this is no longer used in 3.0. The Cluster Role could still make sense for the OpenShift oauth-proxy, but the mapping file won't be used. The credentials database password might need to be [moved/renamed](https://github.com/cryostatio/cryostat-operator/pull/727#discussion_r1543163083).

**Comment by tthvo** [comment]
Thanks Elliott! I would love to help out with those changes anytime once #710 is completed :D

**Comment by ebaron** [comment]
Thanks @tthvo! I will keep this epic open and add any such changes to it.

**Comment by tthvo** [comment]
Hey @ebaron I think its pretty much done in https://github.com/cryostatio/cryostat-operator/pull/808?

**Comment by andrewazores** [comment]
Can this be closed now?

**Comment by ebaron** [comment]
Yeah I think we're done with API changes for 3.0 at this point
