### ISSUE TITLE
Script to check/update license headers

### ISSUE THREAD

**Issue by ebaron** [cryostatio/cryostat-operator#81]
It would be nice to have a simple script that checks source files for license headers, and adds them if they're missing.

**Comment by ebaron** [comment]
We might be able to use this tool as part of our build process: https://github.com/google/addlicense. UPL is not one of the built-in licenses, but it appears to support custom license files with the `-f` option.

**Comment by tthvo** [comment]
@ebaron is this necessary for `2.2.0`? I want to do some small chore work in operator to read more into the source code. So meanwhile I can work on this too.

**Comment by ebaron** [comment]
@tthvo it's not urgent, but please feel free to take it on. It would be helpful for development.
