### ISSUE TITLE
kubectl plugins for creating, stopping, etc. Recordings

### ISSUE THREAD

**Issue by andrewazores** [cryostatio/cryostat-operator#83]
@ebaron

**Comment by ebaron** [comment]
Downloading recordings is another good one

**Comment by ebaron** [comment]
Some reading on kubectl plugins: https://kubernetes.io/docs/tasks/extend-kubectl/kubectl-plugins/

**Comment by ebaron** [comment]
The operator's Recording API has been deprecated with #349. I think this no longer makes sense.
