### ISSUE TITLE
[Bug] v1beta2 CR status is not displayed on OpenShift

### ISSUE THREAD

**Issue by tthvo** [cryostatio/cryostat-operator#842]
### Current Behavior

On the `Cryostat details` page, we can see that the status for v1beta2 CR is displayed with that of v1beta1.

![image](https://github.com/cryostatio/cryostat-operator/assets/68053619/6ac2162a-e0b8-4d8e-ad1c-af9bef360da4)

### Expected Behavior

CR status of v1beta2 should be displayed: `targetNamespaces`, `applicationURL`, `storageSecret`, `databaseSecret`

### Steps To Reproduce

On latest upstream `cryostat3` branch, `make deploy_bundle create_cryostat_cr`.

### Environment

```Markdown
- Fedora 40
- CRC version: 2.26.0+233df0
- OpenShift version: 4.13.9
```

### Anything else?

Is this OpenShift console bug? Or is there some API marker that must be present? Or is there something else I am missing?

**Comment by tthvo** [comment]
Do you see the same issue @cryostatio/maintainers? My OCP cluster is pretty old so that could be the problem.

**Comment by andrewazores** [comment]
@ebaron just noticed more or less the same thing an hour ago, that the UI still looks shows the `v1beta1` spec fields like `minimal`. He's checking with the OCP Console team, it seems like it might be a bug on that side.

**Comment by tthvo** [comment]
Ahh okayy! Hopefully, the issue can be sorted out! Thanks @andrewazores

**Comment by ebaron** [comment]
Filed a bug with the console team: https://issues.redhat.com/browse/OCPBUGS-34901

**Comment by tthvo** [comment]
Not ideal but a workaround for the time-being on our side can be or somehow configure controller-gen to put later versions first in order.

```bash
$ make bundle
$ yq -i '.spec.customresourcedefinitions.owned |= pick([1, 0])' \
  ./bundle/manifests/cryostat-operator.clusterserviceversion.yaml
```

![image](https://github.com/cryostatio/cryostat-operator/assets/68053619/87effa3e-08fe-487e-b89f-1d9c5bcb02a8)

**Comment by tthvo** [comment]
Right thanks, make sense! It makes me wonder if there are any conventions about this crd version order. 

Though, it would be nicer that openshift console team can resolve the bug to check for crd version. But for now, https://github.com/cryostatio/cryostat-operator/pull/852
