### ISSUE TITLE
[Request] Helm chart for the operator

### ISSUE THREAD

**Issue by grzesuav** [cryostatio/cryostat-operator#901]
### Describe the feature

Hi, I would like to install operator using helm chart - can you provide one ? Or is there any already existing

### Anything other information?

N/A

**Comment by andrewazores** [comment]
There is no such thing existing, we have either the Operator or the Helm Chart available. Can you describe what your requirements are that you want the Operator functionality but installable via Helm Chart? Maybe there is another way to accomplish what you need.

**Comment by grzesuav** [comment]
I wanted to install operator via helm as I do not use OLM - like Prometheus operator have helm chart or manifest for its installation. I did not notice any manifest to setup cryostat operator as well.

My use case is simple, wanted to explore how much easier it would be to install cryostat via CRD however I do not see a way to install operator via helm of kubectl apply

**Comment by tthvo** [comment]
> I wanted to install operator via helm as I do not use OLM - like Prometheus operator have helm chart or manifest for its installation. I did not notice any manifest to setup cryostat operator as well.
> 
> My use case is simple, wanted to explore how much easier it would be to install cryostat via CRD however I do not see a way to install operator via helm of kubectl apply

The operator is built as a Go-based operator. See https://sdk.operatorframework.io/docs/building-operators/golang/. Thus, it can't be installed with helm. I don't know if there is any plan for helm-based operator.

But if you are looking for a single yaml file to use with `kubectl apply`. There is a Make target `deploy` (i.e. run `make deploy`) that builds all necessary resources into a single k8s yaml and `kubectl apply` it. You can also build the yaml yourself with kustomize: `kubectl kustomize config/default`. Note: the namespace is default to: `cryostat-operator-system`. Though, this requires you to checkout the source code.

**Comment by andrewazores** [comment]
There are no current plans for such a "helm chart to install the operator". It could be something we investigate, but adding yet another way to install and configure everything seems like it would be a relatively heavy maintenance burden on top of all the rest of the work to develop features and things. It could maybe be something we maintain on a best-effort basis upstream if someone provides it to begin with.

Distributing a `bundle.yaml` seems simple enough and just uses existing Operator tooling, so I can see that being a pretty realistic goal. We could just have a release action that generates this YAML bundle and publishes it somewhere.

**Comment by tthvo** [comment]
> Distributing a bundle.yaml seems simple enough and just uses existing Operator tooling, so I can see that being a pretty realistic goal. We could just have a release action that generates this YAML bundle and publishes it somewhere.

Looks related to #144

> It could maybe be something we maintain on a best-effort basis upstream if someone provides it to begin with.

Right, I was also thinking of having support for upstream only.

**Comment by andrewazores** [comment]
I think #144 got left by the wayside because our Helm chart came into existence not too long after too. That along with getting the Operator published on OperatorHub achieved the original goal there of a "one-click install", since at the time the only installation method available was to clone the git repo and use the Makefile.

**Comment by tthvo** [comment]
Ah make sense! I think it would be nice to solve #144 too to cover above case of "one-click install" with helm/static file. It's pretty common on upstream k8s. For example, cert-manager, nginx, aws acks, and even OLM itself, all distribute a static yaml for use with `kubectl apply`. 

For static field, the only problem I am seeing though is the namespace of resources. Some have annotations that reference "namespace/resource-name", which would be hard to support unless namespace is hard-coded.

**Comment by tthvo** [comment]
>  It could maybe be something we maintain on a best-effort basis upstream if someone provides it to begin with.

https://github.com/arttor/helmify. This looks promising. It might be possible to generate helm chart from static manifest.

**Comment by tthvo** [comment]
> If you are looking for a single yaml file to use with kubectl apply. There is a Make target deploy (i.e. run make deploy) that builds all necessary resources into a single k8s yaml and kubectl apply it. You can also build the yaml yourself with kustomize: kubectl kustomize config/default. Note: the namespace is default to: cryostat-operator-system. Though, this requires you to checkout the source code.

@grzesuav Seems like you can avoid cloning the repo with to get a static manifest. Again, the namespace is hard-coded to `cryostat-operator-system`.

```bash
# Replace ref with any version tag or branch
kubectl kustomize https://github.com/cryostatio/cryostat-operator.git/config/default?ref=v2.4.0
```

**Comment by grzesuav** [comment]
Thanks for the comments, I named the issue `Helm chart` as wasn't aware there is a static manifest or kustomize here, thanks for the pointers !

Re. helming the static manigest, I use sth like 

```
kubectl kustomize ./kustomize | kubectl slice --output-dir ./helm/argocd/templates/base
```
however this helmify look like doing better job, will try it out.


One last thing, if you can add to README or to the documentation that there is static manifes/kustomize, it would be great !
